{"bloqade.task.batch.BatchErrors": {"task_errors": [[0, {"bloqade.task.batch.TaskError": {"exception_type": "AccessDeniedException", "stack_trace": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bloqade/task/batch.py\", line 491, in _submit\n    task.submit(**kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bloqade/task/braket.py\", line 38, in submit\n    self.task_id = self.backend.submit_task(self.task_ir)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bloqade/submission/braket.py\", line 54, in submit_task\n    task = self.device.run(ahs_program, shots=shots)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bloqade/submission/braket.py\", line 28, in device\n    self._device = AwsDevice(self.device_arn)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/braket/aws/aws_device.py\", line 113, in __init__\n    self._aws_session = self._get_session_and_initialize(aws_session or AwsSession())\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/braket/aws/aws_device.py\", line 337, in _get_session_and_initialize\n    self._get_regional_device_session(session)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/braket/aws/aws_device.py\", line 353, in _get_regional_device_session\n    raise (\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/braket/aws/aws_device.py\", line 350, in _get_regional_device_session\n    self._populate_properties(region_session)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/braket/aws/aws_device.py\", line 381, in _populate_properties\n    metadata = session.get_device(self._arn)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/braket/aws/aws_session.py\", line 607, in get_device\n    return self.braket_client.get_device(deviceArn=arn)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/botocore/client.py\", line 565, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/botocore/client.py\", line 1021, in _make_api_call\n    raise error_class(parsed_response, operation_name)\nbotocore.errorfactory.AccessDeniedException: An error occurred (AccessDeniedException) when calling the GetDevice operation: User: arn:aws:iam::051441083726:user/philo is not authorized to perform: braket:GetDevice on resource: arn:aws:braket:us-east-1:051441083726:device/qpu/quera/Aquila\n"}}], [1, {"bloqade.task.batch.TaskError": {"exception_type": "AccessDeniedException", "stack_trace": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bloqade/task/batch.py\", line 491, in _submit\n    task.submit(**kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bloqade/task/braket.py\", line 38, in submit\n    self.task_id = self.backend.submit_task(self.task_ir)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bloqade/submission/braket.py\", line 54, in submit_task\n    task = self.device.run(ahs_program, shots=shots)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bloqade/submission/braket.py\", line 28, in device\n    self._device = AwsDevice(self.device_arn)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/braket/aws/aws_device.py\", line 113, in __init__\n    self._aws_session = self._get_session_and_initialize(aws_session or AwsSession())\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/braket/aws/aws_device.py\", line 337, in _get_session_and_initialize\n    self._get_regional_device_session(session)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/braket/aws/aws_device.py\", line 353, in _get_regional_device_session\n    raise (\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/braket/aws/aws_device.py\", line 350, in _get_regional_device_session\n    self._populate_properties(region_session)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/braket/aws/aws_device.py\", line 381, in _populate_properties\n    metadata = session.get_device(self._arn)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/braket/aws/aws_session.py\", line 607, in get_device\n    return self.braket_client.get_device(deviceArn=arn)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/botocore/client.py\", line 565, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/botocore/client.py\", line 1021, in _make_api_call\n    raise error_class(parsed_response, operation_name)\nbotocore.errorfactory.AccessDeniedException: An error occurred (AccessDeniedException) when calling the GetDevice operation: User: arn:aws:iam::051441083726:user/philo is not authorized to perform: braket:GetDevice on resource: arn:aws:braket:us-east-1:051441083726:device/qpu/quera/Aquila\n"}}], [2, {"bloqade.task.batch.TaskError": {"exception_type": "AccessDeniedException", "stack_trace": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bloqade/task/batch.py\", line 491, in _submit\n    task.submit(**kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bloqade/task/braket.py\", line 38, in submit\n    self.task_id = self.backend.submit_task(self.task_ir)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bloqade/submission/braket.py\", line 54, in submit_task\n    task = self.device.run(ahs_program, shots=shots)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bloqade/submission/braket.py\", line 28, in device\n    self._device = AwsDevice(self.device_arn)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/braket/aws/aws_device.py\", line 113, in __init__\n    self._aws_session = self._get_session_and_initialize(aws_session or AwsSession())\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/braket/aws/aws_device.py\", line 337, in _get_session_and_initialize\n    self._get_regional_device_session(session)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/braket/aws/aws_device.py\", line 353, in _get_regional_device_session\n    raise (\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/braket/aws/aws_device.py\", line 350, in _get_regional_device_session\n    self._populate_properties(region_session)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/braket/aws/aws_device.py\", line 381, in _populate_properties\n    metadata = session.get_device(self._arn)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/braket/aws/aws_session.py\", line 607, in get_device\n    return self.braket_client.get_device(deviceArn=arn)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/botocore/client.py\", line 565, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/botocore/client.py\", line 1021, in _make_api_call\n    raise error_class(parsed_response, operation_name)\nbotocore.errorfactory.AccessDeniedException: An error occurred (AccessDeniedException) when calling the GetDevice operation: User: arn:aws:iam::051441083726:user/philo is not authorized to perform: braket:GetDevice on resource: arn:aws:braket:us-east-1:051441083726:device/qpu/quera/Aquila\n"}}], [3, {"bloqade.task.batch.TaskError": {"exception_type": "AccessDeniedException", "stack_trace": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bloqade/task/batch.py\", line 491, in _submit\n    task.submit(**kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bloqade/task/braket.py\", line 38, in submit\n    self.task_id = self.backend.submit_task(self.task_ir)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bloqade/submission/braket.py\", line 54, in submit_task\n    task = self.device.run(ahs_program, shots=shots)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bloqade/submission/braket.py\", line 28, in device\n    self._device = AwsDevice(self.device_arn)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/braket/aws/aws_device.py\", line 113, in __init__\n    self._aws_session = self._get_session_and_initialize(aws_session or AwsSession())\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/braket/aws/aws_device.py\", line 337, in _get_session_and_initialize\n    self._get_regional_device_session(session)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/braket/aws/aws_device.py\", line 353, in _get_regional_device_session\n    raise (\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/braket/aws/aws_device.py\", line 350, in _get_regional_device_session\n    self._populate_properties(region_session)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/braket/aws/aws_device.py\", line 381, in _populate_properties\n    metadata = session.get_device(self._arn)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/braket/aws/aws_session.py\", line 607, in get_device\n    return self.braket_client.get_device(deviceArn=arn)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/botocore/client.py\", line 565, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/botocore/client.py\", line 1021, in _make_api_call\n    raise error_class(parsed_response, operation_name)\nbotocore.errorfactory.AccessDeniedException: An error occurred (AccessDeniedException) when calling the GetDevice operation: User: arn:aws:iam::051441083726:user/philo is not authorized to perform: braket:GetDevice on resource: arn:aws:braket:us-east-1:051441083726:device/qpu/quera/Aquila\n"}}], [4, {"bloqade.task.batch.TaskError": {"exception_type": "AccessDeniedException", "stack_trace": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bloqade/task/batch.py\", line 491, in _submit\n    task.submit(**kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bloqade/task/braket.py\", line 38, in submit\n    self.task_id = self.backend.submit_task(self.task_ir)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bloqade/submission/braket.py\", line 54, in submit_task\n    task = self.device.run(ahs_program, shots=shots)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bloqade/submission/braket.py\", line 28, in device\n    self._device = AwsDevice(self.device_arn)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/braket/aws/aws_device.py\", line 113, in __init__\n    self._aws_session = self._get_session_and_initialize(aws_session or AwsSession())\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/braket/aws/aws_device.py\", line 337, in _get_session_and_initialize\n    self._get_regional_device_session(session)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/braket/aws/aws_device.py\", line 353, in _get_regional_device_session\n    raise (\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/braket/aws/aws_device.py\", line 350, in _get_regional_device_session\n    self._populate_properties(region_session)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/braket/aws/aws_device.py\", line 381, in _populate_properties\n    metadata = session.get_device(self._arn)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/braket/aws/aws_session.py\", line 607, in get_device\n    return self.braket_client.get_device(deviceArn=arn)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/botocore/client.py\", line 565, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/botocore/client.py\", line 1021, in _make_api_call\n    raise error_class(parsed_response, operation_name)\nbotocore.errorfactory.AccessDeniedException: An error occurred (AccessDeniedException) when calling the GetDevice operation: User: arn:aws:iam::051441083726:user/philo is not authorized to perform: braket:GetDevice on resource: arn:aws:braket:us-east-1:051441083726:device/qpu/quera/Aquila\n"}}], [5, {"bloqade.task.batch.TaskError": {"exception_type": "AccessDeniedException", "stack_trace": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bloqade/task/batch.py\", line 491, in _submit\n    task.submit(**kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bloqade/task/braket.py\", line 38, in submit\n    self.task_id = self.backend.submit_task(self.task_ir)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bloqade/submission/braket.py\", line 54, in submit_task\n    task = self.device.run(ahs_program, shots=shots)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bloqade/submission/braket.py\", line 28, in device\n    self._device = AwsDevice(self.device_arn)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/braket/aws/aws_device.py\", line 113, in __init__\n    self._aws_session = self._get_session_and_initialize(aws_session or AwsSession())\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/braket/aws/aws_device.py\", line 337, in _get_session_and_initialize\n    self._get_regional_device_session(session)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/braket/aws/aws_device.py\", line 353, in _get_regional_device_session\n    raise (\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/braket/aws/aws_device.py\", line 350, in _get_regional_device_session\n    self._populate_properties(region_session)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/braket/aws/aws_device.py\", line 381, in _populate_properties\n    metadata = session.get_device(self._arn)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/braket/aws/aws_session.py\", line 607, in get_device\n    return self.braket_client.get_device(deviceArn=arn)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/botocore/client.py\", line 565, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/botocore/client.py\", line 1021, in _make_api_call\n    raise error_class(parsed_response, operation_name)\nbotocore.errorfactory.AccessDeniedException: An error occurred (AccessDeniedException) when calling the GetDevice operation: User: arn:aws:iam::051441083726:user/philo is not authorized to perform: braket:GetDevice on resource: arn:aws:braket:us-east-1:051441083726:device/qpu/quera/Aquila\n"}}]]}}